version: '3.8'

services:
  pg-ip-whitelister:
    build:
      context: .
      dockerfile: Dockerfile.alpine-optimized
    container_name: pg-ip-whitelister
    ports:
      - "5000:5000"
    environment:
      # Pangolin API Configuration
      - PANGOLIN_API_URL=${PANGOLIN_API_URL}
      - PANGOLIN_API_KEY=${PANGOLIN_API_KEY}
      - PANGOLIN_ORG_ID=${PANGOLIN_ORG_ID}
      
      # Flask Configuration
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
    
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "5", "http://localhost:5000/api/client-ip"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 